---
title: "R Review"
author: "tsy"
date: "2020/5/4"
output: html_document
---

###(1.)Basic Introduction

 **Calculater**
 
 *Example*
 
```{r}
#加
5 + 3
#乘
5 * 3
#除
5 / 3
#次方
5 ^ 3
#餘數
5 %% 3
#商
5 %/% 3

```

```{r}
##Sequence
1:10
seq(1, 10, 2)
#從第一個開始每兩個取一次
seq(1,10, length.out = 6)
#1~10等差取6個數
```
```{r}
##Assign a names to a value
a <- 3 ^ 5
a
```
```{r}
##Special values
NA
NaN
Inf
pi
1e-3
Inf - Inf + 10
signif(83524, digits = 2)
trunc(125.3333)#去掉小數
```
###Descriptive Stastistics

```{r}
x <- 1:25
mean(x)
var(x)
quantile(x, c(0.1, 0.5, 0.7))
##Create a vector
x <- c(1, 3, 5, 7, 9, 11)
y <- c(2, 4, 6, 8, 10, 12)
x
y
z <- c(1:25, NA)
mean(z, na.rm = TRUE) #要把NA去除
summary(z)
boxplot(z)
objects()   #現在有的變數

```
###Vector

```{r}
##Vectors
v1 <- c(1:5)
v2 <- c(3:6)
length(v1)#vector裡面有幾個元素
v1
v1[1]
v1[-1]#刪除第一個
rep(seq(2, 10, 2), 2)
rep(c(1, 4), c(3, 2))
a <- c(3, 4, 2, 7, 10, 23, 8, 9, 11)
sort(a)#按大小排
order(a)#6(sort之後數字原本的index)

```
```{r}
##Character vectors
text1 <- "Hello R World!!!" 
text1
toupper(text1)
colors <- c("red", "yellow", "BLUE")
more.colors <- c(colors, "green", "cyan")
grep("y", more.colors)#有y元素的index
paste(colors, "line")
f.c <- factor(colors)
#[1] red    yellow BLUE  
#Levels: BLUE red yellow(按字母順序排)
##Logical words
T
F
3 > 5
A <- c(T, T, F, T, F)
!A
sum(A)#有幾個TRUE
is.na(NA)
is.na(2)
c(class(2), class('Hello'), class(TRUE))
```

